"""
SQLite → PostgreSQL Migration Script for ScholarZone

This script exports all data from the local SQLite database and generates
a PostgreSQL-compatible SQL file for import.

Usage:
    python migration_export.py                    # Export to migration_export.sql
    python migration_export.py --validate         # Validate SQLite data before export
    python migration_export.py --target postgres  # Direct PostgreSQL import (requires psycopg)

Requirements:
    - SQLAlchemy (already in project)
    - psycopg2 or psycopg (for direct PostgreSQL import)
"""

import argparse
import json
import sqlite3
import sys
from datetime import datetime, date
from decimal import Decimal
from pathlib import Path

SQLITE_PATH = Path(__file__).parent / "scholarzone.db"
OUTPUT_SQL = Path(__file__).parent / "migration_export.sql"


def get_sqlite_tables(conn):
    """Get all table names from SQLite database."""
    cursor = conn.cursor()
    cursor.execute("SELECT name FROM sqlite_master WHERE type='table' ORDER BY name")
    return [row[0] for row in cursor.fetchall()]


def get_table_schema(conn, table_name):
    """Get column info for a table."""
    cursor = conn.cursor()
    cursor.execute(f"PRAGMA table_info({table_name})")
    return cursor.fetchall()


def get_table_data(conn, table_name):
    """Get all rows from a table."""
    cursor = conn.cursor()
    cursor.execute(f"SELECT * FROM {table_name}")
    columns = [desc[0] for desc in cursor.description]
    rows = cursor.fetchall()
    return columns, rows


def get_foreign_keys(conn, table_name):
    """Get foreign key info for a table."""
    cursor = conn.cursor()
    cursor.execute(f"PRAGMA foreign_key_list({table_name})")
    return cursor.fetchall()


def get_create_table_sql(conn, table_name):
    """Get CREATE TABLE SQL."""
    cursor = conn.cursor()
    cursor.execute(f"SELECT sql FROM sqlite_master WHERE name='{table_name}'")
    result = cursor.fetchone()
    return result[0] if result else None


def sqlite_type_to_postgres(sqlite_type):
    """Convert SQLite type to PostgreSQL type."""
    sqlite_type = sqlite_type.upper() if sqlite_type else "TEXT"
    
    type_map = {
        "INTEGER": "INTEGER",
        "INT": "INTEGER",
        "BIGINT": "BIGINT",
        "SMALLINT": "SMALLINT",
        "TINYINT": "SMALLINT",
        "REAL": "DOUBLE PRECISION",
        "FLOAT": "DOUBLE PRECISION",
        "DOUBLE": "DOUBLE PRECISION",
        "NUMERIC": "NUMERIC",
        "DECIMAL": "DECIMAL",
        "BOOLEAN": "BOOLEAN",
        "BOOL": "BOOLEAN",
        "DATE": "DATE",
        "DATETIME": "TIMESTAMP",
        "TIMESTAMP": "TIMESTAMP",
        "TIME": "TIME",
        "BLOB": "BYTEA",
        "BINARY": "BYTEA",
        "VARBINARY": "BYTEA",
    }
    
    # Check for VARCHAR with length
    if sqlite_type.startswith("VARCHAR"):
        return sqlite_type  # PostgreSQL supports VARCHAR(n)
    
    # Check for NUMERIC/DECIMAL with precision
    if sqlite_type.startswith("NUMERIC") or sqlite_type.startswith("DECIMAL"):
        return sqlite_type
    
    return type_map.get(sqlite_type, "TEXT")


def convert_create_table_sql(sqlite_sql):
    """Convert SQLite CREATE TABLE to PostgreSQL compatible SQL."""
    if not sqlite_sql:
        return None
    
    # This is a simplified conversion - for production, use Alembic or pgloader
    pg_sql = sqlite_sql
    
    # Replace AUTOINCREMENT with GENERATED BY DEFAULT AS IDENTITY
    pg_sql = pg_sql.replace("AUTOINCREMENT", "GENERATED BY DEFAULT AS IDENTITY")
    
    # Replace SQLite types
    pg_sql = pg_sql.replace("DATETIME", "TIMESTAMP")
    pg_sql = pg_sql.replace("BOOLEAN", "BOOLEAN")
    
    # Handle JSON type (SQLite stores as TEXT)
    pg_sql = pg_sql.replace("JSON NOT NULL DEFAULT '[]'", "JSONB NOT NULL DEFAULT '[]'")
    pg_sql = pg_sql.replace("JSON NOT NULL DEFAULT '{}'", "JSONB NOT NULL DEFAULT '{}'")
    
    return pg_sql


def format_value_for_pg(value, pg_type="TEXT"):
    """Format a value for PostgreSQL SQL."""
    if value is None:
        return "NULL"
    
    if isinstance(value, bool):
        return "TRUE" if value else "FALSE"
    
    if pg_type == "BOOLEAN" and isinstance(value, int) and not isinstance(value, bool):
        # SQLite stores booleans as integers (1/0); convert to PostgreSQL TRUE/FALSE
        return "TRUE" if value == 1 else "FALSE"
    
    if isinstance(value, (int, float)):
        return str(value)
    
    if isinstance(value, (datetime, date)):
        return f"'{value.isoformat()}'"
    
    if isinstance(value, bytes):
        # Bytea literal
        return f"'\\x{value.hex()}'"
    
    if isinstance(value, (dict, list)):
        # JSON
        json_str = json.dumps(value).replace("'", "''")
        return f"'{json_str}'::jsonb"
    
    # String - escape single quotes
    str_val = str(value).replace("'", "''")
    return f"'{str_val}'"


def validate_sqlite_data(conn):
    """Validate SQLite data before export."""
    cursor = conn.cursor()
    
    print("=== SQLite Data Validation ===\n")
    
    # Check scholarships
    cursor.execute("SELECT COUNT(*) FROM scholarships")
    count = cursor.fetchone()[0]
    print(f"Scholarships: {count}")
    
    cursor.execute("SELECT MAX(id) FROM scholarships")
    max_id = cursor.fetchone()[0]
    print(f"Max scholarship ID: {max_id}")
    
    cursor.execute("SELECT COUNT(*) FROM scholarships WHERE country = 'Test Country'")
    test_count = cursor.fetchone()[0]
    print(f"Test records: {test_count}")
    
    cursor.execute("""
        SELECT official_source_url FROM scholarships 
        WHERE official_source_url IS NOT NULL 
        GROUP BY official_source_url HAVING COUNT(*) > 1
    """)
    dupes = cursor.fetchall()
    print(f"Duplicate URLs: {len(dupes)}")
    
    # Check related tables
    cursor.execute("SELECT COUNT(*) FROM scholarship_verification_history")
    print(f"Verification history: {cursor.fetchone()[0]}")
    
    cursor.execute("SELECT COUNT(*) FROM scholarship_reviews")
    print(f"Scholarship reviews: {cursor.fetchone()[0]}")
    
    # Check for orphaned records
    cursor.execute("""
        SELECT COUNT(*) FROM scholarship_verification_history 
        WHERE scholarship_id NOT IN (SELECT id FROM scholarships)
    """)
    orphaned_history = cursor.fetchone()[0]
    print(f"Orphaned verification history: {orphaned_history}")
    
    cursor.execute("""
        SELECT COUNT(*) FROM scholarship_reviews 
        WHERE scholarship_id NOT IN (SELECT id FROM scholarships)
    """)
    orphaned_reviews = cursor.fetchone()[0]
    print(f"Orphaned reviews: {orphaned_reviews}")
    
    print()
    
    if test_count > 0:
        print("WARNING: Test records found in database!")
        return False
    
    if orphaned_history > 0 or orphaned_reviews > 0:
        print("WARNING: Orphaned records found!")
        return False
    
    print("Validation PASSED")
    return True


def export_to_sql(conn, output_path):
    """Export SQLite data to PostgreSQL-compatible SQL file."""
    tables = get_sqlite_tables(conn)
    
    # Define table order (respect foreign key dependencies)
    table_order = [
        "scholarships",
        "scholarship_verification_history",
        "scholarship_reviews",
        "scholarship_snapshots",
        "scholarship_fetch_attempts",
        "scholarship_restore_records",
        "approved_sources",
        "content_fingerprints",
        "discovery_candidates",
        "knowledge_nodes",
        "knowledge_edges",
        "source_health",
    ]
    
    # Filter to only tables that exist
    ordered_tables = [t for t in table_order if t in tables]
    # Add any remaining tables not in our order list
    ordered_tables += [t for t in tables if t not in table_order]
    
    with open(output_path, "w", encoding="utf-8") as f:
        f.write("-- ScholarZone SQLite → PostgreSQL Migration\n")
        f.write(f"-- Generated: {datetime.utcnow().isoformat()}Z\n")  # noqa: DTZ003
        f.write(f"-- Source: {SQLITE_PATH}\n")
        f.write("--\n")
        f.write("-- IMPORTANT: Run this script against a fresh PostgreSQL database.\n")
        f.write("-- The application will create the schema on first startup.\n")
        f.write("-- This script only contains data INSERT statements.\n")
        f.write("--\n\n")
        
        f.write("BEGIN;\n\n")
        
        for table_name in ordered_tables:
            columns, rows = get_table_data(conn, table_name)
            
            if not rows:
                f.write(f"-- Table {table_name}: 0 rows (skipped)\n\n")
                continue
            
            f.write(f"-- Table {table_name}: {len(rows)} rows\n")
            
            # Get column types
            schema = get_table_schema(conn, table_name)
            col_types = {col[1]: col[2] for col in schema}
            
            for row in rows:
                col_names = ", ".join(columns)
                values = []
                for col, val in zip(columns, row):
                    pg_type = sqlite_type_to_postgres(col_types.get(col, "TEXT"))
                    values.append(format_value_for_pg(val, pg_type))
                
                values_str = ", ".join(values)
                f.write(f"INSERT INTO {table_name} ({col_names}) VALUES ({values_str});\n")
            
            f.write("\n")
        
        f.write("COMMIT;\n")
    
    print(f"Export complete: {output_path}")
    print(f"Total tables: {len(ordered_tables)}")
    
    # Count total rows
    total_rows = 0
    for table_name in ordered_tables:
        _, rows = get_table_data(conn, table_name)
        total_rows += len(rows)
    
    print(f"Total rows: {total_rows}")


def main():
    parser = argparse.ArgumentParser(description="ScholarZone SQLite → PostgreSQL Migration")
    parser.add_argument("--validate", action="store_true", help="Validate SQLite data only")
    parser.add_argument("--output", type=str, default=str(OUTPUT_SQL), help="Output SQL file path")
    args = parser.parse_args()
    
    if not SQLITE_PATH.exists():
        print(f"ERROR: SQLite database not found: {SQLITE_PATH}")
        sys.exit(1)
    
    conn = sqlite3.connect(str(SQLITE_PATH))
    conn.row_factory = sqlite3.Row
    
    try:
        if args.validate:
            valid = validate_sqlite_data(conn)
            sys.exit(0 if valid else 1)
        else:
            # First validate
            print("Validating SQLite data...")
            if not validate_sqlite_data(conn):
                print("\nValidation FAILED. Aborting export.")
                sys.exit(1)
            
            print(f"\nExporting to {args.output}...")
            export_to_sql(conn, Path(args.output))
            
            # Print file size
            output_size = Path(args.output).stat().st_size
            print(f"Output file size: {output_size:,} bytes ({output_size / 1024 / 1024:.2f} MB)")
    
    finally:
        conn.close()


if __name__ == "__main__":
    main()
